package:
  name: poppy-ergo-starter
  # version automatically set in the build.sh and blt.bat

source:
  path: ../


build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 0

requirements:
  build:
    - python
    - setuptools
    - pypot >=3
    - hampy

  run:
    - python
    - pypot >=3
    - opencv3
    - hampy

test:

  # Python imports
  imports:
    - poppy_ergo_starter

about:
  home: https://github.com/poppy-project/poppy-ergo-starter'
  summary: 'Poppy Ergo Starter Software Library'
  license: GNU GENERAL PUBLIC LICENSE Version 3
